name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm test
      - name: Use Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: push to GAS
        run: |
          echo "${{ secrets.CLASPRC_JSON }}" > ~/.clasprc.json
          chmod +x scripts/deploy_gas.sh
          scripts/deploy_gas.sh ${{ secrets.DEPLOY_ID }}
        env:
          CI: true
